
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Oct 11 2023 10:54:55 IST (Oct 11 2023 05:24:55 UTC)

// Verification Directory fv/tx_buff 

module tx_buff(clk, reset, data_in, tx_buff_ld, frame_gen_intl,
     tx_buff_busy, tx_buff_1, tx_buff_2, tx_buff_3, tx_buff_4,
     tx_buff_5, tx_buff_6, tx_buff_7, tx_buff_8, tx_buff_9, tx_buff_10,
     rtr, dlc);
  input clk, reset, tx_buff_ld;
  input [7:0] data_in;
  output frame_gen_intl, tx_buff_busy, rtr;
  output [7:0] tx_buff_1, tx_buff_2, tx_buff_3, tx_buff_4, tx_buff_5,
       tx_buff_6, tx_buff_7, tx_buff_8, tx_buff_9, tx_buff_10;
  output [3:0] dlc;
  wire clk, reset, tx_buff_ld;
  wire [7:0] data_in;
  wire frame_gen_intl, tx_buff_busy, rtr;
  wire [7:0] tx_buff_1, tx_buff_2, tx_buff_3, tx_buff_4, tx_buff_5,
       tx_buff_6, tx_buff_7, tx_buff_8, tx_buff_9, tx_buff_10;
  wire [3:0] dlc;
  wire [3:0] next_state;
  wire [3:0] state;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18,
       UNCONNECTED19, UNCONNECTED20, UNCONNECTED21, UNCONNECTED22;
  wire UNCONNECTED23, UNCONNECTED24, UNCONNECTED25, UNCONNECTED26,
       UNCONNECTED27, UNCONNECTED28, UNCONNECTED29, UNCONNECTED30;
  wire UNCONNECTED31, UNCONNECTED32, UNCONNECTED33, UNCONNECTED34,
       UNCONNECTED35, UNCONNECTED36, UNCONNECTED37, UNCONNECTED38;
  wire UNCONNECTED39, UNCONNECTED40, UNCONNECTED41, UNCONNECTED42,
       UNCONNECTED43, UNCONNECTED44, UNCONNECTED45, UNCONNECTED46;
  wire UNCONNECTED47, UNCONNECTED48, UNCONNECTED49, UNCONNECTED50,
       UNCONNECTED51, UNCONNECTED52, UNCONNECTED53, UNCONNECTED54;
  wire UNCONNECTED55, UNCONNECTED56, UNCONNECTED57, UNCONNECTED58,
       UNCONNECTED59, UNCONNECTED60, UNCONNECTED61, UNCONNECTED62;
  wire UNCONNECTED63, UNCONNECTED64, UNCONNECTED65, UNCONNECTED66,
       UNCONNECTED67, UNCONNECTED68, UNCONNECTED69, UNCONNECTED70;
  wire UNCONNECTED71, UNCONNECTED72, UNCONNECTED73, UNCONNECTED74,
       UNCONNECTED75, UNCONNECTED76, UNCONNECTED77, UNCONNECTED78;
  wire UNCONNECTED79, UNCONNECTED80, UNCONNECTED81, UNCONNECTED82,
       UNCONNECTED83, UNCONNECTED84, UNCONNECTED85, UNCONNECTED86;
  wire UNCONNECTED87, UNCONNECTED88, n_0, n_1, n_2, n_3, n_4, n_5;
  wire n_6, n_7, n_8, n_9, n_10, n_11, n_12, n_13;
  wire n_14, n_15, n_16, n_17, n_18, n_19, n_20, n_21;
  wire n_22, n_23, n_24, n_25, n_26, n_27, n_28, n_29;
  wire n_30, n_31, n_32, n_33, n_34, n_35, n_36, n_37;
  wire n_38, n_39, n_40, n_41, n_42, n_43, n_44, n_45;
  wire n_46, n_47, n_48, n_49, n_50, n_51, n_52, n_53;
  wire n_54, n_55, n_56, n_57, n_58, n_59;
  assign dlc[0] = 1'b0;
  assign dlc[1] = 1'b0;
  assign dlc[2] = 1'b0;
  assign dlc[3] = 1'b0;
  assign rtr = 1'b0;
  assign tx_buff_10[0] = 1'b0;
  assign tx_buff_10[1] = 1'b0;
  assign tx_buff_10[2] = 1'b0;
  assign tx_buff_10[3] = 1'b0;
  assign tx_buff_10[4] = 1'b0;
  assign tx_buff_10[5] = 1'b0;
  assign tx_buff_10[6] = 1'b0;
  assign tx_buff_10[7] = 1'b0;
  assign tx_buff_9[0] = 1'b0;
  assign tx_buff_9[1] = 1'b0;
  assign tx_buff_9[2] = 1'b0;
  assign tx_buff_9[3] = 1'b0;
  assign tx_buff_9[4] = 1'b0;
  assign tx_buff_9[5] = 1'b0;
  assign tx_buff_9[6] = 1'b0;
  assign tx_buff_9[7] = 1'b0;
  assign tx_buff_8[0] = 1'b0;
  assign tx_buff_8[1] = 1'b0;
  assign tx_buff_8[2] = 1'b0;
  assign tx_buff_8[3] = 1'b0;
  assign tx_buff_8[4] = 1'b0;
  assign tx_buff_8[5] = 1'b0;
  assign tx_buff_8[6] = 1'b0;
  assign tx_buff_8[7] = 1'b0;
  assign tx_buff_7[0] = 1'b0;
  assign tx_buff_7[1] = 1'b0;
  assign tx_buff_7[2] = 1'b0;
  assign tx_buff_7[3] = 1'b0;
  assign tx_buff_7[4] = 1'b0;
  assign tx_buff_7[5] = 1'b0;
  assign tx_buff_7[6] = 1'b0;
  assign tx_buff_7[7] = 1'b0;
  assign tx_buff_6[0] = 1'b0;
  assign tx_buff_6[1] = 1'b0;
  assign tx_buff_6[2] = 1'b0;
  assign tx_buff_6[3] = 1'b0;
  assign tx_buff_6[4] = 1'b0;
  assign tx_buff_6[5] = 1'b0;
  assign tx_buff_6[6] = 1'b0;
  assign tx_buff_6[7] = 1'b0;
  assign tx_buff_5[0] = 1'b0;
  assign tx_buff_5[1] = 1'b0;
  assign tx_buff_5[2] = 1'b0;
  assign tx_buff_5[3] = 1'b0;
  assign tx_buff_5[4] = 1'b0;
  assign tx_buff_5[5] = 1'b0;
  assign tx_buff_5[6] = 1'b0;
  assign tx_buff_5[7] = 1'b0;
  assign tx_buff_4[0] = 1'b0;
  assign tx_buff_4[1] = 1'b0;
  assign tx_buff_4[2] = 1'b0;
  assign tx_buff_4[3] = 1'b0;
  assign tx_buff_4[4] = 1'b0;
  assign tx_buff_4[5] = 1'b0;
  assign tx_buff_4[6] = 1'b0;
  assign tx_buff_4[7] = 1'b0;
  assign tx_buff_3[0] = 1'b0;
  assign tx_buff_3[1] = 1'b0;
  assign tx_buff_3[2] = 1'b0;
  assign tx_buff_3[3] = 1'b0;
  assign tx_buff_3[4] = 1'b0;
  assign tx_buff_3[5] = 1'b0;
  assign tx_buff_3[6] = 1'b0;
  assign tx_buff_3[7] = 1'b0;
  assign tx_buff_2[0] = 1'b0;
  assign tx_buff_2[1] = 1'b0;
  assign tx_buff_2[2] = 1'b0;
  assign tx_buff_2[3] = 1'b0;
  assign tx_buff_2[4] = 1'b0;
  assign tx_buff_2[5] = 1'b0;
  assign tx_buff_2[6] = 1'b0;
  assign tx_buff_2[7] = 1'b0;
  assign tx_buff_1[0] = 1'b0;
  assign tx_buff_1[1] = 1'b0;
  assign tx_buff_1[2] = 1'b0;
  assign tx_buff_1[3] = 1'b0;
  assign tx_buff_1[4] = 1'b0;
  assign tx_buff_1[5] = 1'b0;
  assign tx_buff_1[6] = 1'b0;
  assign tx_buff_1[7] = 1'b0;
  assign tx_buff_busy = 1'b0;
  assign frame_gen_intl = 1'b0;
  DFFX1 \next_state_reg[0] (.CLK (clk), .D (n_59), .Q (next_state[0]),
       .QN (UNCONNECTED));
  SDFFX1 \tx_buffers_reg[0][7]260 (.CLK (clk), .D (tx_buff_1[7]), .SI
       (data_in[7]), .SE (n_50), .Q (tx_buff_1[7]), .QN (UNCONNECTED0));
  SDFFX1 \tx_buffers_reg[0][0]253 (.CLK (clk), .D (tx_buff_1[0]), .SI
       (data_in[0]), .SE (n_50), .Q (tx_buff_1[0]), .QN (UNCONNECTED1));
  SDFFX1 \tx_buffers_reg[0][1]254 (.CLK (clk), .D (tx_buff_1[1]), .SI
       (data_in[1]), .SE (n_50), .Q (tx_buff_1[1]), .QN (UNCONNECTED2));
  SDFFX1 \tx_buffers_reg[0][2]255 (.CLK (clk), .D (tx_buff_1[2]), .SI
       (data_in[2]), .SE (n_50), .Q (tx_buff_1[2]), .QN (UNCONNECTED3));
  SDFFX1 \tx_buffers_reg[0][3]256 (.CLK (clk), .D (tx_buff_1[3]), .SI
       (data_in[3]), .SE (n_50), .Q (tx_buff_1[3]), .QN (UNCONNECTED4));
  SDFFX1 \tx_buffers_reg[0][4]257 (.CLK (clk), .D (tx_buff_1[4]), .SI
       (data_in[4]), .SE (n_50), .Q (tx_buff_1[4]), .QN (UNCONNECTED5));
  SDFFX1 \tx_buffers_reg[0][5]258 (.CLK (clk), .D (tx_buff_1[5]), .SI
       (data_in[5]), .SE (n_50), .Q (tx_buff_1[5]), .QN (UNCONNECTED6));
  SDFFX1 \tx_buffers_reg[0][6]259 (.CLK (clk), .D (tx_buff_1[6]), .SI
       (data_in[6]), .SE (n_50), .Q (tx_buff_1[6]), .QN (UNCONNECTED7));
  DFFX1 \next_state_reg[1] (.CLK (clk), .D (n_57), .Q (next_state[1]),
       .QN (UNCONNECTED8));
  OR2X1 g2087__2398(.IN1 (n_58), .IN2 (n_29), .Q (n_59));
  SDFFX1 \tx_buffers_reg[1][6]243 (.CLK (clk), .D (tx_buff_2[6]), .SI
       (tx_buff_1[6]), .SE (n_49), .Q (tx_buff_2[6]), .QN
       (UNCONNECTED9));
  SDFFX1 \tx_buffers_reg[1][3]240 (.CLK (clk), .D (tx_buff_2[3]), .SI
       (tx_buff_1[3]), .SE (n_49), .Q (tx_buff_2[3]), .QN
       (UNCONNECTED10));
  SDFFX1 \tx_buffers_reg[1][4]241 (.CLK (clk), .D (tx_buff_2[4]), .SI
       (tx_buff_1[4]), .SE (n_49), .Q (tx_buff_2[4]), .QN
       (UNCONNECTED11));
  SDFFX1 \tx_buffers_reg[1][5]242 (.CLK (clk), .D (tx_buff_2[5]), .SI
       (tx_buff_1[5]), .SE (n_49), .Q (tx_buff_2[5]), .QN
       (UNCONNECTED12));
  SDFFX1 \tx_buffers_reg[1][2]239 (.CLK (clk), .D (tx_buff_2[2]), .SI
       (tx_buff_1[2]), .SE (n_49), .Q (tx_buff_2[2]), .QN
       (UNCONNECTED13));
  SDFFX1 \tx_buffers_reg[1][7]244 (.CLK (clk), .D (tx_buff_2[7]), .SI
       (tx_buff_1[7]), .SE (n_49), .Q (tx_buff_2[7]), .QN
       (UNCONNECTED14));
  SDFFX1 \tx_buffers_reg[1][0]237 (.CLK (clk), .D (tx_buff_2[0]), .SI
       (tx_buff_1[0]), .SE (n_49), .Q (tx_buff_2[0]), .QN
       (UNCONNECTED15));
  SDFFX1 \tx_buffers_reg[1][1]238 (.CLK (clk), .D (tx_buff_2[1]), .SI
       (tx_buff_1[1]), .SE (n_49), .Q (tx_buff_2[1]), .QN
       (UNCONNECTED16));
  DFFX1 \dlc_reg[3]107 (.CLK (clk), .D (n_54), .Q (dlc[3]), .QN
       (UNCONNECTED17));
  DFFX1 rtr_reg102(.CLK (clk), .D (n_56), .Q (rtr), .QN
       (UNCONNECTED18));
  DFFX1 \dlc_reg[0]104 (.CLK (clk), .D (n_53), .Q (dlc[0]), .QN
       (UNCONNECTED19));
  DFFX1 \dlc_reg[2]106 (.CLK (clk), .D (n_55), .Q (dlc[2]), .QN
       (UNCONNECTED20));
  DFFX1 \dlc_reg[1]105 (.CLK (clk), .D (n_52), .Q (dlc[1]), .QN
       (UNCONNECTED21));
  SDFFX1 \tx_buffers_reg[2][0]221 (.CLK (clk), .D (tx_buff_2[0]), .SI
       (tx_buff_3[0]), .SE (n_46), .Q (tx_buff_3[0]), .QN
       (UNCONNECTED22));
  DFFSSRX1 \next_state_reg[3] (.CLK (clk), .D (n_43), .RSTB
       (next_state[3]), .SETB (n_33), .Q (next_state[3]), .QN
       (UNCONNECTED23));
  DFFX1 \next_state_reg[2] (.CLK (clk), .D (n_51), .Q (next_state[2]),
       .QN (UNCONNECTED24));
  AO222X1 g2104__5107(.IN1 (n_19), .IN2 (tx_buff_ld), .IN3 (n_45), .IN4
       (next_state[0]), .IN5 (n_25), .IN6 (n_3), .Q (n_58));
  AO22X1 g2105__6260(.IN1 (n_47), .IN2 (next_state[1]), .IN3 (n_23),
       .IN4 (n_16), .Q (n_57));
  SDFFX1 \tx_buffers_reg[2][2]223 (.CLK (clk), .D (tx_buff_2[2]), .SI
       (tx_buff_3[2]), .SE (n_46), .Q (tx_buff_3[2]), .QN
       (UNCONNECTED25));
  SDFFX1 \tx_buffers_reg[2][5]226 (.CLK (clk), .D (tx_buff_2[5]), .SI
       (tx_buff_3[5]), .SE (n_46), .Q (tx_buff_3[5]), .QN
       (UNCONNECTED26));
  SDFFX1 \tx_buffers_reg[2][6]227 (.CLK (clk), .D (tx_buff_2[6]), .SI
       (tx_buff_3[6]), .SE (n_46), .Q (tx_buff_3[6]), .QN
       (UNCONNECTED27));
  SDFFX1 \tx_buffers_reg[2][7]228 (.CLK (clk), .D (tx_buff_2[7]), .SI
       (tx_buff_3[7]), .SE (n_46), .Q (tx_buff_3[7]), .QN
       (UNCONNECTED28));
  SDFFX1 \tx_buffers_reg[2][3]224 (.CLK (clk), .D (tx_buff_2[3]), .SI
       (tx_buff_3[3]), .SE (n_46), .Q (tx_buff_3[3]), .QN
       (UNCONNECTED29));
  SDFFX1 \tx_buffers_reg[2][1]222 (.CLK (clk), .D (tx_buff_2[1]), .SI
       (tx_buff_3[1]), .SE (n_46), .Q (tx_buff_3[1]), .QN
       (UNCONNECTED30));
  SDFFX1 \tx_buffers_reg[2][4]225 (.CLK (clk), .D (tx_buff_2[4]), .SI
       (tx_buff_3[4]), .SE (n_46), .Q (tx_buff_3[4]), .QN
       (UNCONNECTED31));
  DFFX1 tx_buff_busy_reg100(.CLK (clk), .D (n_48), .Q (tx_buff_busy),
       .QN (UNCONNECTED32));
  SDFFX1 \tx_buffers_reg[8][0]125 (.CLK (clk), .D (tx_buff_8[0]), .SI
       (tx_buff_9[0]), .SE (n_41), .Q (tx_buff_9[0]), .QN
       (UNCONNECTED33));
  SDFFX1 \tx_buffers_reg[8][1]126 (.CLK (clk), .D (tx_buff_8[1]), .SI
       (tx_buff_9[1]), .SE (n_41), .Q (tx_buff_9[1]), .QN
       (UNCONNECTED34));
  SDFFX1 \tx_buffers_reg[8][2]127 (.CLK (clk), .D (tx_buff_8[2]), .SI
       (tx_buff_9[2]), .SE (n_41), .Q (tx_buff_9[2]), .QN
       (UNCONNECTED35));
  SDFFX1 \tx_buffers_reg[8][3]128 (.CLK (clk), .D (tx_buff_8[3]), .SI
       (tx_buff_9[3]), .SE (n_41), .Q (tx_buff_9[3]), .QN
       (UNCONNECTED36));
  SDFFX1 \tx_buffers_reg[8][4]129 (.CLK (clk), .D (tx_buff_8[4]), .SI
       (tx_buff_9[4]), .SE (n_41), .Q (tx_buff_9[4]), .QN
       (UNCONNECTED37));
  SDFFX1 \tx_buffers_reg[8][5]130 (.CLK (clk), .D (tx_buff_8[5]), .SI
       (tx_buff_9[5]), .SE (n_41), .Q (tx_buff_9[5]), .QN
       (UNCONNECTED38));
  SDFFX1 \tx_buffers_reg[8][6]131 (.CLK (clk), .D (tx_buff_8[6]), .SI
       (tx_buff_9[6]), .SE (n_41), .Q (tx_buff_9[6]), .QN
       (UNCONNECTED39));
  SDFFX1 \tx_buffers_reg[8][7]132 (.CLK (clk), .D (tx_buff_8[7]), .SI
       (tx_buff_9[7]), .SE (n_41), .Q (tx_buff_9[7]), .QN
       (UNCONNECTED40));
  SDFFX1 \tx_buffers_reg[3][0]205 (.CLK (clk), .D (tx_buff_4[0]), .SI
       (tx_buff_3[0]), .SE (n_40), .Q (tx_buff_4[0]), .QN
       (UNCONNECTED41));
  SDFFX1 \tx_buffers_reg[3][1]206 (.CLK (clk), .D (tx_buff_4[1]), .SI
       (tx_buff_3[1]), .SE (n_40), .Q (tx_buff_4[1]), .QN
       (UNCONNECTED42));
  SDFFX1 \tx_buffers_reg[3][2]207 (.CLK (clk), .D (tx_buff_4[2]), .SI
       (tx_buff_3[2]), .SE (n_40), .Q (tx_buff_4[2]), .QN
       (UNCONNECTED43));
  SDFFX1 \tx_buffers_reg[3][3]208 (.CLK (clk), .D (tx_buff_4[3]), .SI
       (tx_buff_3[3]), .SE (n_40), .Q (tx_buff_4[3]), .QN
       (UNCONNECTED44));
  SDFFX1 \tx_buffers_reg[3][4]209 (.CLK (clk), .D (tx_buff_4[4]), .SI
       (tx_buff_3[4]), .SE (n_40), .Q (tx_buff_4[4]), .QN
       (UNCONNECTED45));
  SDFFX1 \tx_buffers_reg[3][5]210 (.CLK (clk), .D (tx_buff_4[5]), .SI
       (tx_buff_3[5]), .SE (n_40), .Q (tx_buff_4[5]), .QN
       (UNCONNECTED46));
  SDFFX1 \tx_buffers_reg[3][6]211 (.CLK (clk), .D (tx_buff_4[6]), .SI
       (tx_buff_3[6]), .SE (n_40), .Q (tx_buff_4[6]), .QN
       (UNCONNECTED47));
  SDFFX1 \tx_buffers_reg[3][7]212 (.CLK (clk), .D (tx_buff_4[7]), .SI
       (tx_buff_3[7]), .SE (n_40), .Q (tx_buff_4[7]), .QN
       (UNCONNECTED48));
  SDFFX1 \tx_buffers_reg[4][0]189 (.CLK (clk), .D (tx_buff_4[0]), .SI
       (tx_buff_5[0]), .SE (n_34), .Q (tx_buff_5[0]), .QN
       (UNCONNECTED49));
  SDFFX1 \tx_buffers_reg[4][1]190 (.CLK (clk), .D (tx_buff_4[1]), .SI
       (tx_buff_5[1]), .SE (n_34), .Q (tx_buff_5[1]), .QN
       (UNCONNECTED50));
  SDFFX1 \tx_buffers_reg[4][2]191 (.CLK (clk), .D (tx_buff_4[2]), .SI
       (tx_buff_5[2]), .SE (n_34), .Q (tx_buff_5[2]), .QN
       (UNCONNECTED51));
  SDFFX1 \tx_buffers_reg[4][3]192 (.CLK (clk), .D (tx_buff_4[3]), .SI
       (tx_buff_5[3]), .SE (n_34), .Q (tx_buff_5[3]), .QN
       (UNCONNECTED52));
  SDFFX1 \tx_buffers_reg[4][4]193 (.CLK (clk), .D (tx_buff_4[4]), .SI
       (tx_buff_5[4]), .SE (n_34), .Q (tx_buff_5[4]), .QN
       (UNCONNECTED53));
  SDFFX1 \tx_buffers_reg[4][5]194 (.CLK (clk), .D (tx_buff_4[5]), .SI
       (tx_buff_5[5]), .SE (n_34), .Q (tx_buff_5[5]), .QN
       (UNCONNECTED54));
  AO22X1 g2136__4319(.IN1 (n_44), .IN2 (rtr), .IN3 (n_42), .IN4
       (data_in[4]), .Q (n_56));
  AO22X1 g2137__8428(.IN1 (n_44), .IN2 (dlc[2]), .IN3 (n_42), .IN4
       (data_in[2]), .Q (n_55));
  AO22X1 g2138__5526(.IN1 (n_44), .IN2 (dlc[3]), .IN3 (n_42), .IN4
       (data_in[3]), .Q (n_54));
  AO22X1 g2139__6783(.IN1 (n_44), .IN2 (dlc[0]), .IN3 (n_42), .IN4
       (data_in[0]), .Q (n_53));
  AO22X1 g2140__3680(.IN1 (n_44), .IN2 (dlc[1]), .IN3 (n_42), .IN4
       (data_in[1]), .Q (n_52));
  AO222X1 g2141__1617(.IN1 (n_37), .IN2 (n_0), .IN3 (n_9), .IN4 (n_10),
       .IN5 (n_32), .IN6 (next_state[2]), .Q (n_51));
  SDFFX1 \tx_buffers_reg[5][4]177 (.CLK (clk), .D (tx_buff_6[4]), .SI
       (tx_buff_5[4]), .SE (n_35), .Q (tx_buff_6[4]), .QN
       (UNCONNECTED55));
  SDFFX1 \tx_buffers_reg[5][5]178 (.CLK (clk), .D (tx_buff_6[5]), .SI
       (tx_buff_5[5]), .SE (n_35), .Q (tx_buff_6[5]), .QN
       (UNCONNECTED56));
  SDFFX1 \tx_buffers_reg[5][6]179 (.CLK (clk), .D (tx_buff_6[6]), .SI
       (tx_buff_5[6]), .SE (n_35), .Q (tx_buff_6[6]), .QN
       (UNCONNECTED57));
  SDFFX1 \tx_buffers_reg[5][7]180 (.CLK (clk), .D (tx_buff_6[7]), .SI
       (tx_buff_5[7]), .SE (n_35), .Q (tx_buff_6[7]), .QN
       (UNCONNECTED58));
  SDFFX1 \tx_buffers_reg[6][0]157 (.CLK (clk), .D (tx_buff_6[0]), .SI
       (tx_buff_7[0]), .SE (n_33), .Q (tx_buff_7[0]), .QN
       (UNCONNECTED59));
  SDFFX1 \tx_buffers_reg[6][1]158 (.CLK (clk), .D (tx_buff_6[1]), .SI
       (tx_buff_7[1]), .SE (n_33), .Q (tx_buff_7[1]), .QN
       (UNCONNECTED60));
  SDFFX1 \tx_buffers_reg[6][2]159 (.CLK (clk), .D (tx_buff_6[2]), .SI
       (tx_buff_7[2]), .SE (n_33), .Q (tx_buff_7[2]), .QN
       (UNCONNECTED61));
  SDFFX1 \tx_buffers_reg[6][3]160 (.CLK (clk), .D (tx_buff_6[3]), .SI
       (tx_buff_7[3]), .SE (n_33), .Q (tx_buff_7[3]), .QN
       (UNCONNECTED62));
  SDFFX1 \tx_buffers_reg[6][4]161 (.CLK (clk), .D (tx_buff_6[4]), .SI
       (tx_buff_7[4]), .SE (n_33), .Q (tx_buff_7[4]), .QN
       (UNCONNECTED63));
  SDFFX1 \tx_buffers_reg[6][5]162 (.CLK (clk), .D (tx_buff_6[5]), .SI
       (tx_buff_7[5]), .SE (n_33), .Q (tx_buff_7[5]), .QN
       (UNCONNECTED64));
  SDFFX1 \tx_buffers_reg[6][6]163 (.CLK (clk), .D (tx_buff_6[6]), .SI
       (tx_buff_7[6]), .SE (n_33), .Q (tx_buff_7[6]), .QN
       (UNCONNECTED65));
  SDFFX1 \tx_buffers_reg[6][7]164 (.CLK (clk), .D (tx_buff_6[7]), .SI
       (tx_buff_7[7]), .SE (n_33), .Q (tx_buff_7[7]), .QN
       (UNCONNECTED66));
  SDFFX1 \tx_buffers_reg[4][6]195 (.CLK (clk), .D (tx_buff_4[6]), .SI
       (tx_buff_5[6]), .SE (n_34), .Q (tx_buff_5[6]), .QN
       (UNCONNECTED67));
  SDFFX1 \tx_buffers_reg[4][7]196 (.CLK (clk), .D (tx_buff_4[7]), .SI
       (tx_buff_5[7]), .SE (n_34), .Q (tx_buff_5[7]), .QN
       (UNCONNECTED68));
  SDFFX1 \tx_buffers_reg[5][0]173 (.CLK (clk), .D (tx_buff_6[0]), .SI
       (tx_buff_5[0]), .SE (n_35), .Q (tx_buff_6[0]), .QN
       (UNCONNECTED69));
  SDFFX1 \tx_buffers_reg[5][1]174 (.CLK (clk), .D (tx_buff_6[1]), .SI
       (tx_buff_5[1]), .SE (n_35), .Q (tx_buff_6[1]), .QN
       (UNCONNECTED70));
  SDFFX1 \tx_buffers_reg[5][2]175 (.CLK (clk), .D (tx_buff_6[2]), .SI
       (tx_buff_5[2]), .SE (n_35), .Q (tx_buff_6[2]), .QN
       (UNCONNECTED71));
  SDFFX1 \tx_buffers_reg[5][3]176 (.CLK (clk), .D (tx_buff_6[3]), .SI
       (tx_buff_5[3]), .SE (n_35), .Q (tx_buff_6[3]), .QN
       (UNCONNECTED72));
  SDFFX1 \tx_buffers_reg[7][0]141 (.CLK (clk), .D (tx_buff_7[0]), .SI
       (tx_buff_8[0]), .SE (n_27), .Q (tx_buff_8[0]), .QN
       (UNCONNECTED73));
  SDFFX1 \tx_buffers_reg[7][1]142 (.CLK (clk), .D (tx_buff_7[1]), .SI
       (tx_buff_8[1]), .SE (n_27), .Q (tx_buff_8[1]), .QN
       (UNCONNECTED74));
  SDFFX1 \tx_buffers_reg[7][2]143 (.CLK (clk), .D (tx_buff_7[2]), .SI
       (tx_buff_8[2]), .SE (n_27), .Q (tx_buff_8[2]), .QN
       (UNCONNECTED75));
  SDFFX1 \tx_buffers_reg[7][3]144 (.CLK (clk), .D (tx_buff_7[3]), .SI
       (tx_buff_8[3]), .SE (n_27), .Q (tx_buff_8[3]), .QN
       (UNCONNECTED76));
  SDFFX1 \tx_buffers_reg[7][4]145 (.CLK (clk), .D (tx_buff_7[4]), .SI
       (tx_buff_8[4]), .SE (n_27), .Q (tx_buff_8[4]), .QN
       (UNCONNECTED77));
  SDFFX1 \tx_buffers_reg[7][5]146 (.CLK (clk), .D (tx_buff_7[5]), .SI
       (tx_buff_8[5]), .SE (n_27), .Q (tx_buff_8[5]), .QN
       (UNCONNECTED78));
  SDFFX1 \tx_buffers_reg[7][6]147 (.CLK (clk), .D (tx_buff_7[6]), .SI
       (tx_buff_8[6]), .SE (n_27), .Q (tx_buff_8[6]), .QN
       (UNCONNECTED79));
  SDFFX1 \tx_buffers_reg[7][7]148 (.CLK (clk), .D (tx_buff_7[7]), .SI
       (tx_buff_8[7]), .SE (n_27), .Q (tx_buff_8[7]), .QN
       (UNCONNECTED80));
  SDFFX1 \tx_buffers_reg[9][0]113 (.CLK (clk), .D (tx_buff_9[0]), .SI
       (tx_buff_10[0]), .SE (n_22), .Q (tx_buff_10[0]), .QN
       (UNCONNECTED81));
  SDFFX1 \tx_buffers_reg[9][1]114 (.CLK (clk), .D (tx_buff_9[1]), .SI
       (tx_buff_10[1]), .SE (n_22), .Q (tx_buff_10[1]), .QN
       (UNCONNECTED82));
  AO22X1 g2170__2802(.IN1 (n_38), .IN2 (tx_buff_busy), .IN3 (n_11),
       .IN4 (n_12), .Q (n_48));
  NAND3X0 g2171__1705(.IN1 (n_30), .IN2 (n_31), .IN3 (n_18), .QN
       (n_47));
  SDFFX1 \tx_buffers_reg[9][4]117 (.CLK (clk), .D (tx_buff_9[4]), .SI
       (tx_buff_10[4]), .SE (n_22), .Q (tx_buff_10[4]), .QN
       (UNCONNECTED83));
  SDFFX1 \tx_buffers_reg[9][5]118 (.CLK (clk), .D (tx_buff_9[5]), .SI
       (tx_buff_10[5]), .SE (n_22), .Q (tx_buff_10[5]), .QN
       (UNCONNECTED84));
  SDFFX1 \tx_buffers_reg[9][6]119 (.CLK (clk), .D (tx_buff_9[6]), .SI
       (tx_buff_10[6]), .SE (n_22), .Q (tx_buff_10[6]), .QN
       (UNCONNECTED85));
  SDFFX1 \tx_buffers_reg[9][7]120 (.CLK (clk), .D (tx_buff_9[7]), .SI
       (tx_buff_10[7]), .SE (n_22), .Q (tx_buff_10[7]), .QN
       (UNCONNECTED86));
  SDFFX1 \tx_buffers_reg[9][2]115 (.CLK (clk), .D (tx_buff_9[2]), .SI
       (tx_buff_10[2]), .SE (n_22), .Q (tx_buff_10[2]), .QN
       (UNCONNECTED87));
  SDFFX1 \tx_buffers_reg[9][3]116 (.CLK (clk), .D (tx_buff_9[3]), .SI
       (tx_buff_10[3]), .SE (n_22), .Q (tx_buff_10[3]), .QN
       (UNCONNECTED88));
  NAND3X0 g2178__5122(.IN1 (n_36), .IN2 (n_8), .IN3 (n_17), .QN (n_50));
  NAND3X0 g2179__8246(.IN1 (n_36), .IN2 (n_8), .IN3 (n_7), .QN (n_49));
  OR3X1 g2180__7098(.IN1 (n_26), .IN2 (n_13), .IN3 (n_19), .Q (n_45));
  OA21X1 g2181__6131(.IN1 (state[3]), .IN2 (n_10), .IN3 (n_39), .Q
       (n_46));
  AO222X1 g2182__1881(.IN1 (n_15), .IN2 (n_20), .IN3 (n_23), .IN4
       (state[3]), .IN5 (n_11), .IN6 (state[2]), .Q (n_43));
  OR3X1 g2183__5115(.IN1 (n_25), .IN2 (n_6), .IN3 (state[0]), .Q
       (n_44));
  INVX0 g2184(.INP (n_40), .ZN (n_39));
  NAND2X0 g2185__7482(.IN1 (n_15), .IN2 (n_24), .QN (n_38));
  OAI21X1 g2186__4733(.IN1 (state[2]), .IN2 (n_10), .IN3 (n_21), .QN
       (n_37));
  AND2X1 g2187__6161(.IN1 (n_29), .IN2 (n_2), .Q (n_42));
  NAND2X0 g2188__9315(.IN1 (n_12), .IN2 (n_23), .QN (n_41));
  NAND2X0 g2189__9945(.IN1 (n_8), .IN2 (n_27), .QN (n_40));
  OAI21X1 g2190__2883(.IN1 (n_2), .IN2 (n_18), .IN3 (n_30), .QN (n_32));
  NAND3X0 g2191__2346(.IN1 (n_20), .IN2 (n_0), .IN3 (n_1), .QN (n_31));
  AOI22X1 g2192__1666(.IN1 (n_12), .IN2 (n_1), .IN3 (n_13), .IN4 (n_2),
       .QN (n_36));
  AO21X1 g2193__7410(.IN1 (n_9), .IN2 (state[1]), .IN3 (n_28), .Q
       (n_35));
  OA21X1 g2194__6417(.IN1 (n_15), .IN2 (n_8), .IN3 (n_27), .Q (n_34));
  OA21X1 g2195__5477(.IN1 (n_10), .IN2 (n_8), .IN3 (n_27), .Q (n_33));
  INVX0 g2196(.INP (n_27), .ZN (n_28));
  NOR2X0 g2197__2398(.IN1 (n_16), .IN2 (n_3), .QN (n_26));
  OR2X1 g2198__5107(.IN1 (n_16), .IN2 (n_1), .Q (n_30));
  AND2X1 g2199__6260(.IN1 (n_13), .IN2 (n_0), .Q (n_29));
  NAND2X0 g2200__4319(.IN1 (n_10), .IN2 (n_12), .QN (n_27));
  INVX0 g2201(.INP (n_24), .ZN (n_25));
  NAND3X0 g2202__8428(.IN1 (n_15), .IN2 (next_state[2]), .IN3 (n_5),
       .QN (n_21));
  NOR2X0 g2203__5526(.IN1 (n_9), .IN2 (n_12), .QN (n_24));
  NAND2X0 g2204__6783(.IN1 (n_18), .IN2 (n_14), .QN (n_23));
  NAND2X0 g2205__3680(.IN1 (n_13), .IN2 (n_12), .QN (n_22));
  NAND2X0 g2206__1617(.IN1 (n_0), .IN2 (state[0]), .QN (n_17));
  NOR2X0 g2207__2802(.IN1 (state[2]), .IN2 (tx_buff_ld), .QN (n_20));
  NOR2X0 g2208__1705(.IN1 (state[3]), .IN2 (state[0]), .QN (n_19));
  NAND2X0 g2209__5122(.IN1 (n_1), .IN2 (state[0]), .QN (n_18));
  DFFARX1 \state_reg[2] (.RSTB (n_4), .CLK (clk), .D (next_state[2]),
       .Q (state[2]), .QN (n_2));
  DFFARX1 \state_reg[0] (.RSTB (n_4), .CLK (clk), .D (next_state[0]),
       .Q (state[0]), .QN (n_3));
  DFFARX1 \state_reg[1] (.RSTB (n_4), .CLK (clk), .D (next_state[1]),
       .Q (state[1]), .QN (n_1));
  DFFARX1 \state_reg[3] (.RSTB (n_4), .CLK (clk), .D (next_state[3]),
       .Q (state[3]), .QN (n_0));
  INVX0 g2214(.INP (n_13), .ZN (n_14));
  INVX0 g2215(.INP (n_10), .ZN (n_11));
  INVX0 g2216(.INP (n_9), .ZN (n_8));
  NAND2X0 g2217__8246(.IN1 (n_0), .IN2 (state[1]), .QN (n_7));
  NOR2X0 g2218__7098(.IN1 (n_0), .IN2 (n_1), .QN (n_6));
  NAND2X0 g2219__6131(.IN1 (state[2]), .IN2 (state[3]), .QN (n_16));
  NOR2X0 g2220__1881(.IN1 (state[0]), .IN2 (state[1]), .QN (n_15));
  NOR2X0 g2221__5115(.IN1 (state[0]), .IN2 (n_1), .QN (n_13));
  NOR2X0 g2222__7482(.IN1 (state[2]), .IN2 (n_0), .QN (n_12));
  NAND2X0 g2223__4733(.IN1 (state[1]), .IN2 (state[0]), .QN (n_10));
  NOR2X0 g2224__6161(.IN1 (state[3]), .IN2 (n_2), .QN (n_9));
  INVX0 g2225(.INP (tx_buff_ld), .ZN (n_5));
  INVX0 g2226(.INP (reset), .ZN (n_4));
endmodule

